[workspace]
members = [
    "cdu",
    "hcc/core",
    "hcc/pushover",
    "hcc/server",
    "pushover/pushover",
    "pushover/po",
    "pop/cli",
    "pop/server"
]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
